stages:
  data_ingestion:
    cmd: python src/Chest_Cancer_Classification/pipeline/stage_1_data_ingestion.py
    deps:
      - src/Chest_Cancer_Classification/pipeline/stage_1_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan_data

  prepare_base_model:
    cmd: python src/Chest_Cancer_Classification/pipeline/stage_2_prepare_base_model.py
    deps:
      - src/Chest_Cancer_Classification/pipeline/stage_2_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model/base_model.h5