from src.Chest_Cancer_Classification.config.configuration import ConfigurationManager
from src.Chest_Cancer_Classification.components.model_trainer import Training
from Chest_Cancer_Classification import logger